version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - ray
    environment:
      - RAY_ADDRESS=ray://ray:10001
    networks:
      - infra-net

  ray:
    image: rayproject/ray:2.10.0
    ports:
      - "8265:8265"   # Ray Dashboard (UI)
      - "10001:10001" # Ray Client protocol port
    command: >
      ray start --head --block --dashboard-host 0.0.0.0 --port=6379 --dashboard-port=8265 --ray-client-server-port=10001
    networks:
      - infra-net

networks:
  infra-net:
