version: "3.9"

services:
  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - ray
    environment:
      - RAY_ADDRESS=ray://ray:10001
    networks:
      - infra-net

  ray:
    build:
      context: ./parallel_ray
    ports:
      - "8265:8265"   # Ray Dashboard (UI)
      - "10001:10001" # Ray Client protocol port
    networks:
      - infra-net

networks:
  infra-net:
